### PR TITLE
support windows 32bit and 64bit.

### PR DESCRIPTION
**Pull request by rexdf**
I have test it. Copy to folder and work.

### CODE REVIEW

**Comment by rexdf** [comment]
#1

**Comment by eddiejessup** [comment]
I don't like that there's duplication of the whole `Crypto` folder, where the only difference is in the imports. Can't you just have the binary files in different folders, and have conditional imports within `AES.py`, `Counter.py` and so on?

For example, have folders 'Binary_osx', 'Binary_win32' and so on, containing all the `.so` files for each machine. Then have a separate folder called `Crypto` with the `.py` files. Then wherever there is an import of a binary file, have platform-specific conditional imports like you have in your branch in `Transcrypt.py`.

For example, in `Crypto/AES.py`, have something like,

```
import blockalgo
if platform == 'darwin':
    from Transcrypt.Binary_osx import _AES
elif platform == 'win32':
    from Transcrypt.Binary_win32 import _AES
...
else:
    raise Exception('Platform unsupported')
```

would this work, and avoid duplicating the whole Crypto library? Sorry if I've missed something, it's a while since I've looked at the code.

**Comment by rexdf** [comment]
Compile will be more complex.  But it seems to be better.

**Comment by rexdf** [comment]
The so files import each others.

**Comment by eddiejessup** [comment]
Do you know about the 'dev' branch with a `setup.py` file that I think does all the compilation (in the osx-only case)? What I did was compile the `.so` files in the 'dev' branch, then add those to the 'master' branch if they had changed. To keep the release version as small as possible. Maybe using that would help to sort out the compilation?

**Comment by eddiejessup** [comment]
I'm not sure what the problem is with the `.so` files importing each other. If each set of binary files are in separate folders, they will just import the files in their same folder, which is what we want right?

**Comment by rexdf** [comment]
distutils will not work without exact version of Visual Studio(2010). I install a higher version(2013) , but I used cmake to build it. And it works well.


```c
Py_CLEAR(_counter_module);
	_counter_module = PyImport_ImportModule("Transcrypt.Crypto._counter");
```

I just rewrite the cmake files and generate the files:

transcrpt

That means I need to change at runtime but not build time. And patch the c file.

**Comment by rexdf** [comment]
patch prefix is much easy than dynamic postfix.   Only one `Crypto`  --> `Crypto_win`. But `_counter` `AES` `cpuid`  `galois`  `strxor` have five name to patch. maybe include many C file at each build time to change source code.

For prefix just search and replace in all files and it works.

**Comment by eddiejessup** [comment]
Haha ok, let me know if you've any problems.

**Comment by rexdf** [comment]
It does much more complex. I do not want to do it right now.

And the simplest way is to manually download corresponding file and put them into the folder.

**Comment by eddiejessup** [comment]
Maybe it's simpler to have folders with each set of binaries, then at install-time physically move the correct architecture ones into the `Crypto` folder using `shutil.move`. Then once that's done, there is no need to change any of the rest of the code. I suppose It's basically the same as what Emmet does, but just bundling all the binaries instead of downloading the correct ones.

Anyway obviously don't do it if you don't want, I'll probably get round to doing it at some point, now that I've thought about it.

**Comment by rexdf** [comment]
Now I close it.

**Pull request closed without merging**
