### PR TITLE
support all platform  including win32 win64 linux_86 linux_x86_64

### PR DESCRIPTION
**Pull request by rexdf**
we can easily put a linux x86 x86_64 binary zip and it should work.

### CODE REVIEW

**Comment by rexdf** [comment]
Finally, I think that you can merge it this time.

**Comment by eddiejessup** [comment]
Ok this looks like a good solution, thanks! Why do you check for Python 3? What bit depends on the version?

**Comment by eddiejessup** [comment]
One other thing that is only for my own curiosity: when you do `import maxsize as _maxsize`, and `import platform as _platform`, is there a reason you rename the variable? Is this something that is good practice for some reason? I'm not saying it's wrong, I just haven't seen this before.

**Comment by rexdf** [comment]
I copy it from emmet and I am not sure about it. Maybe it is used to support sublime text 2 (python 2).

**Comment by rexdf** [comment]
Someone says that import maxsize maybe pollute the environment variable scope.  In this situation, it does not need to do so.

**Comment by eddiejessup** [comment]
Ok thanks. I renamed the repository transcrypt -> Transcrypt, since I realised it needed to be capitalised to work for a manual install -- oops! Thanks again for the help.

**Comment by rexdf** [comment]
Yes, the capital problem trouble me for a little while until I find out package control is capital. I learn much from it too. It's the first time that I had built python binary module.

**Comment by eddiejessup** [comment]
Can you tell me what exactly you did to compile the binaries? So that I can do it myself in future.

**Comment by rexdf** [comment]
`python setup.py build`  and run  four virtual machine  for building it.

**Comment by rexdf** [comment]
Nothing Special. All you need is python 3.3.3 for linux and 3.3 for windows.

For windows, 1) comment `#include <cpuid.h>` and change `inline` to `_inline`

For linux , pyenv helps a lot.

**Comment by eddiejessup** [comment]
Could you explain what you mean a bit more? Do you mean, to make the binary file for Windows, I should:

1) Get the source
2) Comment out `#include <cpuid.h>` from `cpuid.c`
3) Rename everywhere `inline` to `_inline`
4) In Windows, get python 3.3
5) In Windows, compile the source using `python setup.py build`
6) Zip up the `.so` files

**Comment by rexdf** [comment]
when run `python setup.py build`, you will get error line number. It seems just 2 patches.

**Pull request merged**
